# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishingwall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalWishing', models.IntegerField()),
            ],
        ),
    ]
