# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wishingwall', '0004_auto_20160503_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishing',
            name='wPassword',
            field=models.CharField(default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='wishing',
            name='wData',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 6, 5, 15, 3, 50406, tzinfo=utc)),
        ),
    ]
