# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wishingwall', '0005_auto_20160506_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishing',
            name='wData',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
